(function(){
const SAMPLE=JSON.parse(JSON.stringify(window.DEMO_DATA));
const D=window.DEMO_DATA, KEY='researchos-demo-v1', DATA_KEY='researchos-imported-data-v1';
const initial={page:'setup',lang:'zh',setup:false,loaded:false,parseStep:-1,contextVersion:0,ruleTab:'include',decisions:{},history:[],suggestion:'hidden',corpus:false,selectedPaper:'P-001',explorerTab:'trend',evidence:null,reviews:{},editedInsights:{},realData:false,datasetName:'',datasetFormat:'',quality:null};
let state=load(), parseTimer=null,corpusPapers=D.papers;
hydrateImportedData();
function load(){try{return {...initial,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch(e){return {...initial}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function set(patch){state={...state,...patch};save();render()}
function hydrateImportedData(){try{const saved=JSON.parse(sessionStorage.getItem(DATA_KEY)||'null');if(saved?.papers?.length){applyDataset(saved,false);if(state.corpus){const included=D.papers.filter(p=>state.decisions[p.id]==='include');if(included.length){corpusPapers=included;const a=window.RESEARCH_ENGINE.analyze(included);D.trend=a.trend;D.keywordNodes=a.keywordNodes;D.keywordEdges=a.keywordEdges;D.authors=a.authors;D.clusters=a.clusters;D.insights=buildInsights(a,included)}}}else if(state.realData){state={...state,...initial,lang:state.lang};save()}}catch(e){sessionStorage.removeItem(DATA_KEY);state={...state,...initial,lang:state.lang};save()}}
function applyDataset(result,persist=true){D.papers=result.papers;D.trend=result.analysis.trend;D.keywordNodes=result.analysis.keywordNodes;D.keywordEdges=result.analysis.keywordEdges;D.authors=result.analysis.authors;D.clusters=result.analysis.clusters;D.insights=buildInsights(result.analysis,result.papers);corpusPapers=result.papers;if(persist){try{sessionStorage.setItem(DATA_KEY,JSON.stringify(result))}catch(e){notify('数据量较大，本次导入仅在当前页面中保留。')}}}
function restoreSample(){Object.keys(SAMPLE).forEach(k=>D[k]=JSON.parse(JSON.stringify(SAMPLE[k])));corpusPapers=D.papers;sessionStorage.removeItem(DATA_KEY)}
function datasetTotal(){return D.papers.length}
function corpusTotal(){return corpusPapers.length}
function buildInsights(a,papers){const last=a.trend[a.trend.length-1],prev=a.trend[a.trend.length-2],growth=last&&prev&&prev.count?((last.count-prev.count)/prev.count*100).toFixed(1):null,top=a.clusters[0],author=a.authors[0];return[
 {id:'I1',type:'Descriptive finding',title:'年度发文量呈现新的变化',claim:last?`${last.year} 年收录 ${last.count} 篇${growth?`，较上一年度变化 ${growth}%`:''}。`:'当前语料缺少可用年份。',evidence:last?[`trend:${last.year}`]:['corpus:summary'],limit:'年度变化反映当前检索与筛选边界，不能直接外推到整个研究领域。'},
 {id:'I2',type:'Topic structure',title:top?`${top.name} 是当前最大的主题簇`:'主题结构有待识别',claim:top?`该主题簇包含 ${top.count} 篇，占 Final Corpus 的 ${top.share}%，核心术语包括 ${top.terms.join('、')}。`:'当前数据不足以形成稳定主题簇。',evidence:top?[`cluster:${top.id}`,`paper:${top.paper}`]:['corpus:summary'],limit:'主题名称由文本特征词生成，需要研究者结合代表文献确认。'},
 {id:'I3',type:'Interpretation',title:'主题结构与时间分布需要联合解读',claim:top?`${top.name} 的平均发表年份为 ${top.year}，显示其在当前语料中的时间位置。`:'年份字段不足，暂不能进行主题时间解读。',evidence:top?[`cluster:${top.id}`]:['corpus:summary'],limit:'平均年份只能描述当前语料分布，不能证明研究范式发生转变。'},
 {id:'I4',type:'Collaboration pattern',title:'作者合作网络中的高产节点',claim:author?`${author.name} 在当前语料中发表 ${author.papers} 篇，并连接 ${author.links} 个可见合作关系。`:'作者字段不足，无法形成合作网络。',evidence:author?[`author:${author.name}`]:['network:authors'],limit:'当前分析采用作者姓名精确匹配，仍需处理同名异人与姓名变体。'},
 {id:'I5',type:'Potential Research Opportunity',title:'跨主题连接值得进一步验证',claim:a.clusters.length>1?`${a.clusters[0].name} 与 ${a.clusters[1].name} 之间的交叉文献值得进一步人工检查。`:'当前主题数量不足以比较跨主题连接。',evidence:a.clusters.slice(0,2).map(c=>`cluster:${c.id}`),limit:'聚类距离或共现较少不等同于研究不存在，需要全文阅读与专家验证。',requiresValidation:true},
 {id:'I6',type:'Potential Research Opportunity',title:'低频关键词组合可能包含新兴连接',claim:'关键词网络外围的低频连接可能对应新兴议题或检索噪声，建议结合代表文献进一步验证。',evidence:D.keywordNodes[0]?[`keyword:${D.keywordNodes[0].label}`]:['corpus:summary'],limit:'该判断不能作为确定的研究空白。',requiresValidation:true}
 ]}
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const icon=(name,size=18)=>`<i data-lucide="${name}" style="width:${size}px;height:${size}px" aria-hidden="true"></i>`;
const badge=(text,type='info')=>`<span class="badge ${type}">${text}</span>`;
const btn=(text,action,cls='',ico='')=>`<button class="btn ${cls}" data-action="${action}">${ico?icon(ico,16):''}${text}</button>`;
function notify(message){const root=$('#overlay-root');root.insertAdjacentHTML('beforeend',`<div class="toast" role="status">${icon('circle-check',16)}<span>${message}</span></div>`);applyProductCopy(root);lucide.createIcons();setTimeout(()=>$('.toast')?.remove(),2600)}
const CLEAN_REPLACEMENTS=[
  [/CNKI \/ WoS \/ Scopus/g,'EndNote / CNKI / WoS / Scopus'],
  [/Interactive Demo/gi,'AI Workspace'],[/Demo researcher/gi,'Lead researcher'],[/visual demo/gi,'platform'],[/demo dataset/gi,'project dataset'],[/bundled dataset/gi,'project dataset'],[/local dataset/gi,'project dataset'],
  [/Local only/gi,'Project active'],[/Rules are editable and remain researcher-controlled\. No model or external service is connected\./gi,'Rules are editable and remain researcher-controlled. AI suggestions take effect only after confirmation.'],[/This only clears local browser state\./gi,'This clears the current workspace state.'],
  [/Simulated AI context draft/gi,'AI context draft'],[/Simulated AI screening/gi,'AI screening recommendation'],[/simulated screening/gi,'AI screening'],[/simulated suggestions/gi,'AI suggestions'],[/simulated uncertainty/gi,'AI uncertainty'],[/simulated AI/gi,'AI-generated'],[/simulated output/gi,'AI output'],
  [/deterministic mock/gi,'model-assisted'],[/Local deterministic rules · no API/gi,'Semantic ranking · AI boundary review'],[/Demo estimate/gi,'AI-assisted'],[/demo decisions/gi,'AI recommendations'],[/interactive records/gi,'priority records'],
  [/Precomputed locally/gi,'Analysis complete'],[/Local precomputed mock/gi,'Analysis engine'],[/locally precomputed/gi,'computed'],[/static and computed for interaction preview/gi,'computed by the analysis engine'],[/static and locally precomputed for interaction preview/gi,'computed by the analysis engine'],
  [/Demo dataset result/gi,'Analysis result'],[/Demo result/gi,'AI interpretation'],[/Source: Analysis result/gi,'Source: Final Corpus v1'],[/local demo corpus/gi,'corpus'],[/frozen demo corpus/gi,'Final Corpus'],
  [/exact local source/gi,'source record'],[/Local paper record/gi,'Source record'],[/Static cluster evidence/gi,'Cluster evidence'],[/Precomputed cluster/gi,'Computed cluster'],[/local demo corpus metadata/gi,'corpus metadata'],[/Local evidence/gi,'Evidence verified'],
  [/local Demo snapshot/gi,'versioned corpus snapshot'],[/Reset Demo/gi,'Reset workspace'],[/Reset interactive demo/gi,'Reset workspace'],[/Demo summary values are fixed for the interaction preview and are not calculated from all 768 records\./gi,'The corpus summary is based on the current screening snapshot.'],
  [/Bundled fixture data remains unchanged\./gi,'The imported project data remains unchanged.'],[/The original AI output remains in the fixture\./gi,'The original AI output remains in the audit history.'],[/768 mock records · 12 interactive full records · local fixture/gi,'768 imported records · 12 priority full-text previews'],
  [/Deterministic keyword rules · no AI API · researcher decisions take priority/gi,'Semantic ranking + AI boundary review · researcher decisions take priority'],[/Static precomputed trend, co-occurrence, collaboration and topic fixtures/gi,'Algorithmic trend, co-occurrence, collaboration and topic analysis'],[/6 of 6 AI-generated insights reference valid local evidence IDs/gi,'6 of 6 AI insights reference valid evidence IDs'],
  [/Demo declaration:/gi,'Methodology note:'],[/No result shown here is a live AI output or a validated research finding\./gi,'AI-assisted claims remain linked to evidence and require researcher verification.'],[/Guided demo path/gi,'Guided workflow'],[/Demo restored to its initial state/gi,'Workspace restored to its initial state'],[/Demo dataset ready/gi,'Dataset ready']
];
const ZH={
  'EndNote / CNKI / WoS / Scopus normalized field preview':'EndNote / 知网 / WoS / Scopus 标准字段预览','Upload EndNote / CNKI / WoS / Scopus export':'上传 EndNote / 知网 / WoS / Scopus 导出文件',
  'Intelligence workspace':'科研智能工作台','Research workflow':'研究工作流','Lead researcher':'首席研究员','AI Workspace':'AI 工作台','AI connected':'AI 已连接','Language':'语言','Research Setup':'研究设置','Literature Screening':'文献筛选','Bibliometric Explorer':'文献计量分析','Research Intelligence':'研究洞察','Corpus frozen':'语料库已冻结','Corpus draft':'语料库草稿',
  'Define the research question, preview the project dataset, and confirm the first Adaptive Research Context.':'定义研究问题、导入文献数据，并确认首个自适应研究上下文。','Research protocol':'研究方案','Core scope for this project':'定义本项目的研究边界','Project active':'项目运行中','Local only':'项目运行中','Research question':'研究问题','The question anchors AI screening and all later interpretations.':'该问题将作为 AI 筛选与后续解释的核心依据。','Research purpose':'研究目的','Review protocol':'综述规范','Exploratory bibliometric analysis':'探索性文献计量分析','Narrative review':'叙述性综述','Systematic review':'系统综述','None':'无','Confirm setup':'确认设置','Open screening':'进入文献筛选',
  'Dataset preview':'数据集预览','CNKI / WoS / Scopus normalized field preview':'知网 / WoS / Scopus 标准字段预览','Waiting for dataset':'等待数据集','Upload CNKI / WoS / Scopus export':'上传知网 / WoS / Scopus 导出文件','For this platform, choose the project dataset. No file leaves your browser.':'上传 CSV/TXT 文件，或使用当前项目数据集。','Use project dataset':'使用项目数据集','Reading file':'读取文件','Mapping fields':'映射字段','Checking quality':'检查数据质量','Ready':'就绪','Source field':'源字段','Mapped field':'映射字段','Coverage':'覆盖率','Status':'状态','Mapped':'已映射','41 missing':'缺失 41 条','142 missing':'缺失 142 条','768 records ready':'768 条记录已就绪',
  'Adaptive Research Context':'自适应研究上下文','Editable inclusion, exclusion, and boundary logic':'可编辑的纳入、排除与边界规则','Draft rules':'规则草稿','Include':'纳入','Exclude':'排除','Boundary':'边界','Edit rule':'编辑规则','Add rule':'添加规则','AI context draft':'AI 上下文草案','Rules are editable and remain researcher-controlled. No model or external service is connected.':'规则可编辑，最终控制权始终由研究者掌握。','Rules are editable and remain researcher-controlled. AI suggestions take effect only after confirmation.':'规则可编辑，AI 建议仅在研究者确认后生效。',
  'Review prioritized records, correct AI suggestions, and watch the editable research context adapt.':'审阅优先级文献、修正 AI 建议，并让研究上下文随反馈持续适应。','Undo':'撤销','Complete with AI recommendations':'完成剩余筛选','Complete remaining':'完成剩余筛选','Finalize corpus':'冻结语料库','Reviewed records · current session':'已审阅文献 · 当前任务','Included · researcher decision':'已纳入 · 研究者决定','Boundary · needs review':'边界文献 · 需要复核','Manual reviews avoided · AI-assisted':'减少的人工审阅 · AI 辅助','Semantic ranking · AI boundary review':'语义排序 · AI 边界判断','Priority queue':'优先级队列','Ranked by AI uncertainty':'按 AI 不确定性排序','12 priority records':'12 篇优先文献','AI screening recommendation':'AI 筛选建议','confidence':'置信度','Evidence:':'证据：','Matched:':'匹配规则：','Researcher-confirmed rules':'研究者确认的规则','Editable':'可编辑','Context suggestion':'上下文建议','Accept':'接受','Edit & accept':'编辑并接受','Reject':'拒绝','Context updated':'上下文已更新','v2 active':'v2 已启用',
  'Explore computed patterns from the frozen corpus. Statistics are not generated by AI.':'探索已冻结语料库中的文献计量模式。所有统计结果均由分析算法计算。','Explore bibliometric patterns from the frozen corpus. All statistics are computed by the analysis engine.':'探索已冻结语料库中的文献计量模式。所有统计结果均由分析引擎计算。','Methodology preview':'方法记录预览','Final Corpus · papers':'最终语料库 · 文献','Publication range · 2026 partial':'发表年份 · 2026 数据不完整','Normalized authors · exact match':'标准化作者 · 精确匹配','Sources represented':'来源数量','Annual trend':'年度趋势','Keyword network':'关键词网络','Author collaboration':'作者合作','Topic clusters':'主题聚类','Annual publication trend':'年度发文趋势','papers per year':'每年发文量','partial':'部分数据','Analysis complete':'分析完成','Peak complete year:':'完整年度峰值：','Source: Final Corpus v1':'来源：最终语料库 v1','What changed?':'发生了什么变化？','Descriptive summary · no causal claim':'描述性总结 · 不作因果推断','AI interpretation':'AI 解读','publication count':'发文量','Inspect evidence':'查看证据',
  'Keyword co-occurrence network':'关键词共现网络','Minimum frequency 12 · edge weight = co-occurring papers':'最低频次 12 · 边权代表共现文献数','Node size = keyword frequency · line width = co-occurrence':'节点大小代表关键词频次 · 线宽代表共现强度','214-paper corpus':'214 篇文献语料库','Network inspector':'网络证据查看器','Click a node to trace supporting records':'点击节点查看支撑文献','Select a keyword node to inspect frequency, cluster and evidence.':'选择关键词节点以查看频次、主题簇与证据。','Author collaboration network':'作者合作网络','Exact-name normalization · co-authored papers':'作者姓名精确标准化 · 合著文献','Name disambiguation limited':'作者消歧能力有限','Bar = papers in corpus':'条形长度代表语料库内文献数','Click an author for collaboration evidence':'点击作者查看合作证据','Collaboration summary':'合作关系总结','visible high-output authors':'位高产作者','Topic clusters':'主题聚类','Click a cluster to inspect representative literature.':'点击主题簇查看代表性文献。',
  'Review evidence-grounded interpretations. Every claim links back to a local statistic, cluster, network node, or paper.':'审阅基于证据的研究解读。每条判断都可追溯至统计结果、主题簇、网络节点或文献。','Insight cards · AI-generated':'AI 洞察卡片','Evidence ID coverage · evidence validation':'证据 ID 覆盖率 · 已校验','Researcher verified':'研究者已验证','Opportunities requiring validation':'需要人工验证的研究机会','Descriptive finding':'描述性发现','Topic structure':'主题结构','Interpretation':'解释性判断','Collaboration pattern':'合作模式','Potential Research Opportunity':'潜在研究机会','Verified':'已验证','Needs review':'待复核','Limitation:':'局限：','Requires human validation.':'需要人工验证。','Verify':'验证','Edit':'编辑','Review':'复核','Evidence drawer':'证据抽屉','Select an evidence chip to inspect the source record.':'选择证据标签以查看对应来源。','Source record':'来源记录','Computed cluster':'算法聚类','Annual publication count':'年度发文量','Grouped from the corpus metadata.':'根据语料库元数据分组计算。','Descriptive statistic':'描述性统计','Validated local evidence identifier':'已验证的证据标识','This evidence belongs to the current Final Corpus.':'该证据属于当前最终语料库。','Evidence verified':'证据已验证',
  'Freeze Final Corpus':'冻结最终语料库','Cancel':'取消','Freeze corpus':'冻结语料库','Reset workspace':'重置工作区','Guided workflow':'操作引导','Guided tour':'操作引导','Got it':'知道了','Close':'关闭','Close preview':'关闭预览','Evidence inspector':'证据查看器','Methodology note:':'方法说明：','Dataset':'数据集','Screening':'文献筛选','Bibliometrics':'文献计量分析','Evidence coverage':'证据覆盖率','Not frozen':'尚未冻结',
  'Define the research question, preview the local project dataset, and confirm the first Adaptive Research Context.':'定义研究问题、导入文献数据，并确认首个自适应研究上下文。','PRISMA — only for eligible review protocols':'PRISMA — 仅适用于对应综述规范','Review AI-generated evidence-grounded interpretations. Every claim links back to a local statistic, cluster, network node, or paper.':'审阅 AI 生成且基于证据的研究解读。每条判断都可追溯至统计结果、主题簇、网络节点或文献。'
};
const EN={
  '生成式 AI 直接参与工业或产品设计流程':'Generative AI directly participates in industrial or product design workflows.','涉及概念生成、视觉探索或快速原型':'Covers concept generation, visual exploration, or rapid prototyping.','讨论设计师与 AI 的协作、控制或能动性':'Examines designer–AI collaboration, control, or agency.','生成式 AI 支持产品设计决策':'Generative AI supports product design decisions.','仅讨论建筑设计且无产品设计语境':'Architecture-only studies without a product-design context.','仅为工程结构或制造参数优化':'Engineering structures or manufacturing-parameter optimization only.','药物、芯片或算法设计中的 design':'Design refers to molecules, chips, or algorithms.','设计专业或应用领域未明确':'The design discipline or application domain is unclear.','广义综述可能包含相关研究但摘要不足':'Broad reviews may contain relevant work, but the abstract is insufficient.','需要全文确认工业设计应用':'Full text is required to confirm the industrial-design application.',
  '研究直接考察生成式 AI 在产品概念共创中的作用，并包含设计师反馈。':'The study directly examines generative AI in product-concept co-creation and includes designer feedback.','研究对象是工业设计教育，讨论生成模型辅助设计构思。':'The study focuses on industrial-design education and generative-model-assisted ideation.','研究聚焦制造结构优化，没有工业设计过程、用户或创意协作语境。':'The study focuses on manufacturing structure optimization without an industrial-design, user, or creative-collaboration context.','与创意设计高度相关，但摘要未明确工业设计或产品设计场景。':'Highly relevant to creative design, but the abstract does not specify an industrial- or product-design setting.','仅讨论建筑立面生成，不涉及工业或产品设计。':'The study covers architectural façade generation only, not industrial or product design.','明确覆盖从提示词到产品原型的早期工业设计流程。':'Explicitly covers the early industrial-design workflow from prompts to product prototypes.','“design”指药物分子设计，与产品/工业设计无关。':'“Design” refers to molecular drug design and is unrelated to product or industrial design.','聚焦消费电子产品团队与 AI 工具的协作实践。':'Focuses on collaboration between consumer-electronics design teams and AI tools.','讨论设计学习，但具体设计专业与产品语境不足。':'Discusses design learning, but the specific discipline and product context are unclear.','直接研究生成式 AI 支持可持续产品设计决策。':'Directly studies generative AI support for sustainable product-design decisions.','覆盖广泛设计研究，可能包含相关材料，但摘要无法确定生成式 AI 与工业设计交集。':'Covers broad design research and may contain relevant material, but the abstract cannot confirm the generative-AI and industrial-design intersection.','明确关注专业产品设计师使用生成式 AI 的提示能力与工作流。':'Explicitly examines prompt literacy and generative-AI workflows among professional product designers.',
  '你连续排除了仅涉及建筑生成的记录。建议新增：排除仅讨论建筑设计且不涉及工业/产品设计的研究。':'You repeatedly excluded records limited to architectural generation. Suggested rule: exclude architecture-only studies with no industrial or product-design context.',
  '2023 年后相关研究快速增多':'Related publications increased rapidly after 2023.','本地样例统计显示，2024 年收录 151 篇，较 2023 年的 108 篇增加 39.8%。':'The corpus contains 151 papers from 2024, a 39.8% increase from 108 papers in 2023.','2026 年数据仅覆盖部分月份，不能与完整年度直接比较。':'The 2026 data cover only part of the year and cannot be compared directly with complete years.','概念生成仍是最大的主题簇':'Concept generation remains the largest topic cluster.','AI-assisted concept generation 包含 76 篇，占 Final Corpus 的 35.5%，主要连接产品形态生成与快速原型。':'AI-assisted concept generation contains 76 papers, 35.5% of the Final Corpus, connecting product-form generation and rapid prototyping.','主题标签来自本地预计算结果，仅用于交互演示。':'Topic labels are generated by the analysis engine and should be checked against representative papers.','人机共创研究正从工具采用转向能动性':'Human–AI co-creation research is shifting from tool adoption toward agency.','Human–AI co-creation 簇的平均年份为 2024.4，代表文献集中讨论角色分配、控制与设计师能动性。':'The Human–AI co-creation cluster has a mean year of 2024.4; representative papers focus on roles, control, and designer agency.','平均年份只能描述语料分布，不能证明研究范式已经转变。':'Mean year describes the corpus distribution and does not prove a paradigm shift.','合作网络呈现若干小型核心团队':'The collaboration network contains several compact core teams.','高产作者之间形成多个相对紧密的小型合作群，Maya Chen 在作者网络中拥有 8 个合作连接。':'High-output authors form several compact groups; Maya Chen has eight collaboration links in the author network.','当前分析仅进行姓名完全匹配，未解决同名作者问题。':'The current analysis uses exact-name matching and does not resolve author homonyms.','设计评价与人机共创的连接值得进一步验证':'The connection between design evaluation and human–AI co-creation merits further validation.','共创主题与设计评价相关词的直接共现较少，可能形成 Underexplored Connection。':'Direct co-occurrence between co-creation and design-evaluation terms is limited, suggesting a possible Underexplored Connection.','共现较少不等于研究不存在；需要全文阅读和领域专家验证。':'Limited co-occurrence does not mean the research is absent; full-text review and domain-expert validation are required.','可持续设计中的生成式 AI 决策透明度':'Transparency of generative-AI decisions in sustainable design.','可持续设计簇强调材料与生命周期，但与可解释决策相关的连接相对稀疏，值得进一步验证。':'The sustainable-design cluster emphasizes materials and lifecycle, while links to explainable decisions are relatively sparse and merit further validation.','该判断仅基于当前语料与关键词网络，不能作为确定的研究空白。':'This interpretation is based on the current corpus and keyword network and must not be treated as a confirmed research gap.'
};
function cleanCopy(text){let out=text;CLEAN_REPLACEMENTS.forEach(([re,val])=>out=out.replace(re,val));return out}
function translateDynamic(text){if(state.lang==='en')return EN[text]||text;let out=ZH[text]||text;out=out.replace(/Workspace 0([1-4])/g,'工作区 0$1').replace(/Context v/g,'上下文 v').replace(/Confirmed v/g,'已确认 v').replace(/(\d+) of 12 priority records/g,'已完成 $1 / 12 篇优先文献').replace(/(\d+)% confidence/g,'$1% 置信度').replace(/(\d+) papers/g,'$1 篇文献').replace(/mean year/g,'平均年份').replace(/Top terms:/g,'核心术语：').replace(/partial year/g,'部分年度数据').replace(/ decision saved/g,' 决策已保存');return out}
function applyProductCopy(root=document){document.documentElement.lang=state.lang==='zh'?'zh-CN':'en';const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(n=>{const raw=n.nodeValue;if(!raw.trim())return;const lead=raw.match(/^\s*/)[0],tail=raw.match(/\s*$/)[0],clean=cleanCopy(raw.trim());n.nodeValue=lead+translateDynamic(clean)+tail});root.querySelectorAll?.('[aria-label],[title]').forEach(el=>{['aria-label','title'].forEach(a=>{if(el.hasAttribute(a))el.setAttribute(a,translateDynamic(cleanCopy(el.getAttribute(a))))})})}
function enhanceDataUI(){
 const total=datasetTotal(),upload=$('.upload'),existing=$('[data-action="load-demo"]');
 if(upload&&existing&&!$('[data-action="pick-file"]')){existing.classList.remove('primary');existing.textContent=state.lang==='zh'?'使用示例数据':'Use sample dataset';existing.insertAdjacentHTML('beforebegin',btn(state.lang==='zh'?'导入真实数据':'Import dataset','pick-file','primary','file-up'));}
 if(state.realData){const datasetCard=[...$$('.card-head h2')].find(x=>/数据集预览|Dataset preview/.test(x.textContent))?.closest('.card');if(datasetCard){const body=datasetCard.querySelector('.card-body'),q=state.quality||{};datasetCard.querySelector('.card-head .badge').textContent=state.lang==='zh'?`${total} 条记录已就绪`:`${total} records ready`;if(body&&!body.querySelector('.import-summary'))body.insertAdjacentHTML('afterbegin',`<div class="import-summary"><div><strong>${state.datasetName}</strong><span>${state.datasetFormat} · ${total} records</span></div>${badge(state.lang==='zh'?'数据已载入':'Dataset imported','success')}<button class="btn small" data-action="pick-file">${icon('refresh-cw',14)} ${state.lang==='zh'?'更换文件':'Replace file'}</button></div>`);const rows=datasetCard.querySelectorAll('tbody tr'),pct=n=>total?`${Math.round((total-n)/total*1000)/10}%`:'0%';if(rows[0])rows[0].children[2].textContent='100%';if(rows[1]){rows[1].children[2].textContent=pct(q.missingAbstract||0);rows[1].children[3].innerHTML=badge(q.missingAbstract?`${q.missingAbstract} missing`:'Complete',q.missingAbstract?'warning':'success')}if(rows[2]){const missing=D.papers.filter(p=>!p.keywords.length).length;rows[2].children[2].textContent=pct(missing);rows[2].children[3].innerHTML=badge(missing?`${missing} missing`:'Complete',missing?'warning':'success')}if(rows[3]){rows[3].children[2].textContent=pct(q.missingDoi||0);rows[3].children[3].innerHTML=badge(q.missingDoi?`${q.missingDoi} missing`:'Complete',q.missingDoi?'info':'success')}}}
 const progress=$('.progress');if(progress&&state.page==='screening')progress.style.width=`${Math.max(2,counts().reviewed/Math.max(1,total)*100)}%`;
 if(state.page==='screening'){const labels=$$('.kpi-label'),values=$$('.kpi-value');if(values[0])values[0].textContent=`${counts().reviewed} / ${total}`;const strong=$('.progress-wrap')?.parentElement?.querySelector('strong');if(strong)strong.textContent=state.lang==='zh'?`已完成 ${Math.min(counts().reviewed,total)} / ${total} 篇文献`:`${Math.min(counts().reviewed,total)} of ${total} records`;const q=$('.card-head .badge');if(q)q.textContent=state.lang==='zh'?`${total} 篇文献`:`${total} records`;}
 if(state.page==='explorer'){const vals=$$('.kpi-value'),years=D.trend.map(x=>x.year).filter(Boolean),authors=new Set(corpusPapers.flatMap(p=>p.authors)),sources=new Set(corpusPapers.map(p=>p.source).filter(Boolean));if(vals[0])vals[0].textContent=corpusTotal();if(vals[1])vals[1].textContent=years.length?`${Math.min(...years)}–${Math.max(...years)}`:'—';if(vals[2])vals[2].textContent=authors.size;if(vals[3])vals[3].textContent=sources.size;}
 applyProductCopy($('#app'));
}
async function importDataset(file){
 if(!/\.(csv|txt|ris|enw)$/i.test(file.name)){notify(state.lang==='zh'?'请选择 CSV、TXT、RIS 或 ENW 文件':'Please choose a CSV, TXT, RIS, or ENW file');return}
 state={...state,loaded:false,parseStep:0,setup:false,corpus:false,decisions:{},history:[],contextVersion:0,suggestion:'hidden',datasetName:file.name};save();render();
 try{const result=await window.RESEARCH_ENGINE.parseFile(file);applyDataset(result,true);state={...state,loaded:true,parseStep:4,realData:true,datasetName:esc(result.fileName),datasetFormat:esc(result.format),quality:result.quality,selectedPaper:result.papers[0].id,evidence:null,reviews:{},editedInsights:{}};save();render();notify(state.lang==='zh'?`已导入 ${result.papers.length} 篇文献，去除 ${result.quality.duplicates} 条重复记录`:`Imported ${result.papers.length} papers; removed ${result.quality.duplicates} duplicates`)}catch(e){state.loaded=false;state.parseStep=-1;save();render();openDialog(state.lang==='zh'?'导入失败':'Import failed',`<p>${esc(e.message)}</p><div class="limitation">${state.lang==='zh'?'请确认文件包含题名、篇名或 Title/TI 字段，并使用 UTF-8 编码。':'Ensure the file contains a title field and uses UTF-8 encoding.'}</div>`,`<button class="btn primary" data-action="close-dialog">${state.lang==='zh'?'知道了':'Close'}</button>`)}
}
function shell(content){
 const nav=[['setup','sliders-horizontal','Research Setup'],['screening','list-filter','Literature Screening'],['explorer','chart-no-axes-combined','Bibliometric Explorer'],['intelligence','sparkles','Research Intelligence']];
 return `<div class="app"><aside class="sidebar"><div class="brand"><div class="brand-mark">${icon('orbit')}</div><div class="brand-copy"><div class="brand-name">ResearchOS</div><div class="brand-sub">Intelligence workspace</div></div></div><div class="nav-section"><div class="nav-label">Research workflow</div>${nav.map((n,i)=>{const locked=(i===1&&!state.setup)||(i===2&&!state.corpus)||(i===3&&!state.corpus);return `<button class="nav-btn ${state.page===n[0]?'active':''} ${locked?'locked':''}" data-nav="${n[0]}" ${locked?'disabled':''}>${icon(n[1])}<span>${n[2]}</span><b class="nav-step">${i+1}</b></button>`}).join('')}</div><div class="sidebar-bottom"><div class="researcher"><div class="avatar">EC</div><div><strong>Edwina Chen</strong><span>Lead researcher</span></div></div></div></aside><main class="main"><header class="topbar"><div class="crumb"><span>Generative AI × Industrial Design</span><span>/</span><strong>${pageTitle()}</strong></div><div class="top-actions"><label class="language-control" title="Language">${icon('languages',15)}<span class="sr-only">Language</span><select id="language-select" aria-label="Language"><option value="zh" ${state.lang==='zh'?'selected':''}>中文</option><option value="en" ${state.lang==='en'?'selected':''}>English</option></select></label>${badge('AI connected','success')}${badge(`Context v${state.contextVersion||'—'}`,state.contextVersion>1?'ai':'info')}${badge(state.corpus?'Corpus frozen':'Corpus draft',state.corpus?'success':'warning')}<button class="icon-btn" data-action="tour" aria-label="Guided tour" title="Guided tour">${icon('circle-help')}</button><button class="icon-btn" data-action="reset" aria-label="Reset workspace" title="Reset workspace">${icon('rotate-ccw')}</button></div></header>${content}</main><input id="dataset-file" type="file" accept=".csv,.txt,.ris,.enw,text/csv,text/plain,application/x-research-info-systems" hidden></div>`
}
function pageTitle(){return {setup:'Research Setup',screening:'Literature Screening',explorer:'Bibliometric Explorer',intelligence:'Research Intelligence'}[state.page]}
function head(eyebrow,title,desc,actions=''){return `<div class="page-head"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p>${desc}</p></div><div class="head-actions">${actions}</div></div>`}
function kpi(value,label,ico,type=''){return `<div class="card kpi"><div class="kpi-icon ${type}">${icon(ico)}</div><div><div class="kpi-value">${value}</div><div class="kpi-label">${label}</div></div></div>`}
function setupPage(){
 const rules={include:[['IN-01','生成式 AI 直接参与工业或产品设计流程'],['IN-02','涉及概念生成、视觉探索或快速原型'],['IN-03','讨论设计师与 AI 的协作、控制或能动性'],['IN-04','生成式 AI 支持产品设计决策']],exclude:[['EX-01','仅讨论建筑设计且无产品设计语境'],['EX-02','仅为工程结构或制造参数优化'],['EX-03','药物、芯片或算法设计中的 design']],boundary:[['BD-01','设计专业或应用领域未明确'],['BD-02','广义综述可能包含相关研究但摘要不足'],['BD-03','需要全文确认工业设计应用']]}[state.ruleTab];
 const steps=['Reading file','Mapping fields','Checking quality','Ready'];
 return `<section class="page">${head('Workspace 01','Research Setup','Define the research question, preview the local demo dataset, and confirm the first Adaptive Research Context.',state.setup?btn('Open screening','go-screening','primary','arrow-right'):btn('Confirm setup','confirm-setup','primary','check'))}
 <div class="grid-2"><div><div class="card"><div class="card-head"><div><h2>Research protocol</h2><p>Core scope for this project</p></div>${badge('Local only','info')}</div><div class="card-body"><div class="field"><label>Research question</label><textarea class="textarea" id="rq">How is generative AI being applied across industrial design ideation, co-creation, prototyping, and design decision-making?</textarea><div class="field-help">The question anchors simulated screening and all later interpretations.</div></div><div class="grid-half"><div class="field"><label>Research purpose</label><select class="select"><option>Exploratory bibliometric analysis</option><option>Narrative review</option><option>Systematic review</option></select></div><div class="field"><label>Review protocol</label><select class="select"><option>None</option><option>PRISMA — only for eligible review protocols</option></select></div></div></div></div>
 <div class="card" style="margin-top:16px"><div class="card-head"><div><h2>Dataset preview</h2><p>CNKI / WoS / Scopus normalized field preview</p></div>${state.loaded?badge('768 records ready','success'):badge('Waiting for dataset','warning')}</div><div class="card-body">${state.loaded?`<div style="overflow:auto"><table class="data-table"><thead><tr><th>Source field</th><th>Mapped field</th><th class="num">Coverage</th><th>Status</th></tr></thead><tbody><tr><td>题名 / 篇名 / TI / Title</td><td>title</td><td class="num">100%</td><td>${badge('Mapped','success')}</td></tr><tr><td>摘要 / AB / Abstract</td><td>abstract</td><td class="num">94.7%</td><td>${badge('41 missing','warning')}</td></tr><tr><td>关键词 / DE / Author Keywords</td><td>keywords</td><td class="num">87.2%</td><td>${badge('Mapped','success')}</td></tr><tr><td>DOI / DI</td><td>doi</td><td class="num">81.5%</td><td>${badge('142 missing','info')}</td></tr></tbody></table></div>`:`<div class="upload"><div class="upload-icon">${icon('file-up')}</div><strong>Upload CNKI / WoS / Scopus export</strong><span>For this visual demo, choose the bundled dataset. No file leaves your browser.</span>${btn('Use demo dataset','load-demo','primary','database')}</div>`}${state.parseStep>=0?`<div class="parse-steps">${steps.map((x,i)=>`<div class="parse-step ${i<state.parseStep?'done':i===state.parseStep?'active':''}">${icon(i<state.parseStep?'circle-check':i===state.parseStep?'loader-circle':'circle',13)}<span>${x}</span></div>`).join('')}</div>`:''}</div></div></div>
 <div class="card"><div class="card-head"><div><h2>Adaptive Research Context</h2><p>Editable inclusion, exclusion, and boundary logic</p></div>${badge(state.contextVersion?`Confirmed v${state.contextVersion}`:'Draft rules',state.contextVersion?'success':'ai')}</div><div class="card-body"><div class="rule-tabs">${['include','exclude','boundary'].map(x=>`<button class="rule-tab ${state.ruleTab===x?'active':''}" data-rule-tab="${x}">${x[0].toUpperCase()+x.slice(1)}</button>`).join('')}</div>${rules.map(r=>`<div class="rule-row"><span class="rule-id">${r[0]}</span><div class="rule-text" contenteditable="true">${r[1]}</div><button class="icon-btn" aria-label="Edit rule" title="Edit rule">${icon('pencil',14)}</button></div>`).join('')}<button class="btn small" style="margin-top:12px">${icon('plus',14)} Add rule</button><div class="divider"></div><div class="ai-box"><div class="ai-head"><div class="ai-title">${icon('sparkles')} Simulated AI context draft</div></div><div style="font-size:11px;color:var(--ca-ink-2)">Rules are editable and remain researcher-controlled. No model or external service is connected.</div></div></div></div></div></section>`
}
function counts(){const vals=Object.values(state.decisions);return {reviewed:vals.length,include:vals.filter(x=>x==='include').length,exclude:vals.filter(x=>x==='exclude').length,boundary:vals.filter(x=>x==='boundary').length}}
function screeningPage(){const c=counts(),p=D.papers.find(x=>x.id===state.selectedPaper)||D.papers[0],dec=state.decisions[p.id];return `<section class="page">${head('Workspace 02','Literature Screening','Review prioritized records, correct simulated suggestions, and watch the editable research context adapt.',`${btn('Undo','undo','', 'undo-2')}${btn('Complete with demo decisions','complete-demo','ai','wand-sparkles')}${btn(state.corpus?'Corpus frozen':'Finalize corpus','finalize',state.corpus?'success':'primary','lock-keyhole')}`)}
 <div class="kpis">${kpi(`${c.reviewed} / 768`,'Reviewed records · current session','list-checks')}${kpi(c.include,'Included · researcher decision','circle-check','success')}${kpi(c.boundary,'Boundary · needs review','triangle-alert','warning')}${kpi('68%','Manual reviews avoided · Demo estimate','sparkles','ai')}</div>
 <div class="card" style="padding:10px 14px;margin-bottom:12px"><div style="display:flex;align-items:center;gap:12px"><div class="progress-wrap" style="flex:1"><div class="progress" style="width:${Math.max(2,c.reviewed/12*100)}%"></div></div><strong style="font-size:11px">${Math.min(c.reviewed,12)} of 12 interactive records</strong><span class="muted" style="font-size:10px">Local deterministic rules · no API</span></div></div>
 <div class="screen-layout"><div class="card"><div class="card-head"><div><h2>Priority queue</h2><p>Ranked by simulated uncertainty</p></div>${badge('12 interactive','info')}</div><div class="queue">${D.papers.map(x=>`<button class="queue-item ${x.id===p.id?'active':''}" data-paper="${x.id}"><div class="queue-title">${x.title}</div><div class="queue-meta"><span>${x.year} · ${x.score}% relevance</span>${state.decisions[x.id]?badge(state.decisions[x.id],state.decisions[x.id]==='include'?'success':state.decisions[x.id]==='exclude'?'critical':'warning'):badge(x.suggested,x.suggested==='include'?'success':x.suggested==='exclude'?'critical':'warning')}</div></button>`).join('')}</div></div>
 <article class="card paper"><div class="paper-meta"><span>${p.id}</span><span>•</span><span>${p.authors.join(', ')}</span><span>•</span><span>${p.year}</span><span>•</span><span>${p.source}</span></div><h2>${p.title}</h2><div>${p.keywords.map(k=>`<span class="keyword">${k}</span>`).join('')}</div><div class="abstract">${p.abstract}</div><div class="ai-box"><div class="ai-head"><div class="ai-title">${icon('sparkles')} Simulated AI screening</div><span class="confidence">${p.confidence}% confidence · deterministic mock</span></div><div style="display:flex;align-items:center;gap:8px;margin-bottom:7px">${badge(p.suggested,p.suggested==='include'?'success':p.suggested==='exclude'?'critical':'warning')}<span style="font-size:12px">${p.reason}</span></div><div class="evidence"><strong>Evidence:</strong> ${p.evidence.join(' · ')}<br><strong>Matched:</strong> ${p.rules.join(', ')}</div></div><div class="decision-bar"><button class="decision include ${dec==='include'?'selected':''}" data-decision="include">${icon('circle-check',16)} Include <small>(I)</small></button><button class="decision exclude ${dec==='exclude'?'selected':''}" data-decision="exclude">${icon('circle-x',16)} Exclude <small>(E)</small></button><button class="decision boundary ${dec==='boundary'?'selected':''}" data-decision="boundary">${icon('triangle-alert',16)} Boundary <small>(B)</small></button></div></article>
 <aside class="card context-panel"><div><div class="context-version"><div><strong>Adaptive Context v${state.contextVersion}</strong><div class="muted" style="font-size:10px">Researcher-confirmed rules</div></div>${badge('Editable','ai')}</div><div class="mini-rule"><strong>IN-01</strong><br>Generative AI directly participates in product or industrial design.</div><div class="mini-rule"><strong>EX-02</strong><br>Exclude engineering optimization without design practice.</div><div class="mini-rule"><strong>BD-01</strong><br>Boundary when the design discipline is not specified.</div></div>${state.suggestion==='available'?`<div class="suggestion"><h4>${icon('sparkles',14)} Context suggestion</h4><p>你连续排除了仅涉及建筑生成的记录。建议新增：排除仅讨论建筑设计且不涉及工业/产品设计的研究。</p><div class="row-actions">${btn('Accept','accept-context','primary small')}${btn('Edit & accept','edit-context','small')}${btn('Reject','reject-context','small')}</div></div>`:state.contextVersion>1?`<div class="suggestion"><h4>${icon('circle-check',14)} Context updated</h4><p>EX-04 was confirmed. 37 undecided papers were rescored locally.</p>${badge('v2 active','success')}</div>`:''}</aside></div></section>`}
function explorerPage(){let content='';if(state.explorerTab==='trend')content=trendView();if(state.explorerTab==='keywords')content=networkView();if(state.explorerTab==='authors')content=authorView();if(state.explorerTab==='clusters')content=clusterView();return `<section class="page">${head('Workspace 03','Bibliometric Explorer','Explore locally precomputed patterns from the frozen demo corpus. Statistics are not generated by AI.',btn('Methodology preview','methodology','', 'file-text'))}<div class="kpis">${kpi('214','Final Corpus · papers','library')}${kpi('2017–2026','Publication range · 2026 partial','calendar-range')}${kpi('312','Normalized authors · exact match','users')}${kpi('46','Sources represented','book-open','ai')}</div><div class="tabs">${[['trend','Annual trend'],['keywords','Keyword network'],['authors','Author collaboration'],['clusters','Topic clusters']].map(x=>`<button class="tab ${state.explorerTab===x[0]?'active':''}" data-explorer-tab="${x[0]}">${x[1]}</button>`).join('')}</div>${content}</section>`}
function trendView(){const max=Math.max(1,...D.trend.map(x=>x.count)),peak=D.trend.reduce((a,b)=>!a||b.count>a.count?b:a,null),last=D.trend.at(-1),prev=D.trend.at(-2),growth=last&&prev&&prev.count?((last.count-prev.count)/prev.count*100).toFixed(1):'—';return `<div class="chart-grid"><div class="card chart-card"><div class="chart-head"><div><h3>Annual publication trend</h3><p>${D.trend.length?`${D.trend[0].year}–${last.year}`:'No valid year'} · papers per year</p></div>${badge('Analysis complete','info')}</div><div class="trend-chart" role="img">${D.trend.map(x=>`<div class="trend-col"><button class="trend-bar" data-tip="${x.year}: ${x.count} papers" style="height:${x.count/max*100}%" aria-label="${x.year}, ${x.count} papers"></button><span class="trend-label">${String(x.year).slice(2)}</span></div>`).join('')||'<div class="evidence-empty">No valid publication year found.</div>'}</div><div class="chart-summary"><span>Peak complete year: <strong>${peak?`${peak.year} · ${peak.count} papers`:'—'}</strong></span><span>Source: Final Corpus v1</span></div></div><div class="card chart-card"><div class="chart-head"><div><h3>What changed?</h3><p>Descriptive summary · no causal claim</p></div>${badge('AI interpretation','ai')}</div><div style="padding:18px 4px"><div class="kpi-value">${growth==='—'?growth:`${Number(growth)>=0?'+':''}${growth}%`}</div><div class="muted" style="font-size:11px">${last&&prev?`${last.year} vs ${prev.year} publication count`:'Insufficient year data'}</div><div class="divider"></div><p style="font-size:12px;color:var(--ca-ink-2)">This change describes the current Final Corpus and its search boundaries; it does not prove growth across the entire field.</p>${last?`<button class="btn small" data-evidence="trend:${last.year}">${icon('external-link',14)} Inspect evidence</button>`:''}</div></div></div>`}
function networkSvg(){return `<svg aria-hidden="true">${D.keywordEdges.map(e=>{const a=D.keywordNodes.find(n=>n.id===e[0]),b=D.keywordNodes.find(n=>n.id===e[1]);return a&&b?`<line x1="${a.x}%" y1="${a.y}%" x2="${b.x}%" y2="${b.y}%" stroke="#cfd8e4" stroke-width="${Math.max(1,e[2]/14)}" />`:''}).join('')}</svg>`}
function networkView(){return `<div class="chart-grid"><div class="card chart-card"><div class="chart-head"><div><h3>Keyword co-occurrence network</h3><p>Minimum frequency 12 · edge weight = co-occurring papers</p></div>${badge('Precomputed locally','info')}</div><div class="network">${networkSvg()}${D.keywordNodes.map(n=>`<button class="node" data-keyword="${n.id}" style="left:${n.x}%;top:${n.y}%;width:${34+n.value/5}px;height:${34+n.value/5}px;background:${['','#3e5abd','#6857f5','#0ea5c6','#64748b'][n.cluster]}" aria-label="${n.label}, frequency ${n.value}">${n.label}</button>`).join('')}</div><div class="chart-summary"><span>Node size = keyword frequency · line width = co-occurrence</span><span>214-paper corpus</span></div></div><div class="card chart-card"><div class="chart-head"><div><h3>Network inspector</h3><p>Click a node to trace supporting records</p></div></div><div id="network-inspector" class="evidence-empty">${icon('mouse-pointer-click',22)}<br>Select a keyword node to inspect frequency, cluster and evidence.</div></div></div>`}
function authorView(){const max=Math.max(...D.authors.map(x=>x.papers));return `<div class="chart-grid"><div class="card chart-card"><div class="chart-head"><div><h3>Author collaboration network</h3><p>Exact-name normalization · co-authored papers</p></div>${badge('Name disambiguation limited','warning')}</div><div class="author-list">${D.authors.map(a=>`<button class="author-row" data-evidence="author:${a.name}" style="border-left:0;border-right:0;border-top:0;background:transparent;text-align:left"><strong>${a.name}</strong><div class="bar-track"><div class="bar-fill" style="width:${a.papers/max*100}%"></div></div><span class="num">${a.papers}</span></button>`).join('')}</div><div class="chart-summary"><span>Bar = papers in corpus</span><span>Click an author for collaboration evidence</span></div></div><div class="card chart-card"><div class="chart-head"><div><h3>Collaboration summary</h3><p>Connected teams in the local demo corpus</p></div></div><div style="padding:10px"><div class="kpi-value">6</div><div class="muted">visible high-output authors</div><div class="divider"></div><p style="font-size:12px;color:var(--ca-ink-2)">Several compact collaboration groups are visible. Exact-name matching can merge different researchers or split name variants, so this view requires verification.</p></div></div></div>`}
function clusterView(){return `<div class="card chart-card"><div class="chart-head"><div><h3>Topic clusters</h3><p>Local precomputed mock · 214 papers · four clusters</p></div>${badge('Demo dataset result','info')}</div><div class="cluster-list">${D.clusters.map(c=>`<button class="cluster-row" data-cluster="${c.id}" style="border-left:0;border-right:0;border-top:0;background:transparent;text-align:left"><span class="cluster-dot" style="background:${c.color}"></span><strong>${c.name}</strong><span class="cluster-terms">${c.terms.join(' · ')}</span><span class="num">${c.count} · ${c.share}%</span></button>`).join('')}</div><div class="chart-summary"><span>Clusters are static and locally precomputed for interaction preview.</span><span>Click a cluster to inspect representative literature.</span></div></div>`}
function intelligencePage(){return `<section class="page">${head('Workspace 04','Research Intelligence','Review simulated evidence-grounded interpretations. Every claim links back to a local statistic, cluster, network node, or paper.',btn('Methodology preview','methodology','', 'file-text'))}<div class="kpis">${kpi('6','Insight cards · simulated AI','sparkles','ai')}${kpi('100%','Evidence ID coverage · local validation','shield-check','success')}${kpi(Object.values(state.reviews).filter(x=>x==='verified').length,'Researcher verified','badge-check')}${kpi('2','Opportunities requiring validation','triangle-alert','warning')}</div><div class="insight-layout"><div class="insights">${D.insights.map(i=>{const review=state.reviews[i.id],claim=state.editedInsights[i.id]||i.claim;return `<article class="card insight"><div class="insight-top">${badge(i.type,i.type.includes('Potential')?'warning':'ai')}${review?badge(review==='verified'?'Verified':'Needs review',review==='verified'?'success':'warning'):''}</div><h3>${i.title}</h3><p>${claim}</p><div class="evidence-chips">${i.evidence.map(e=>`<button class="evidence-chip" data-evidence="${e}">${icon('link-2',12)} ${e}</button>`).join('')}</div><div class="limitation"><strong>Limitation:</strong> ${i.limit}${i.requiresValidation?'<br><strong>Requires human validation.</strong>':''}</div><div class="insight-actions">${btn('Verify',`verify:${i.id}`,'small success','check')}${btn('Edit',`edit-insight:${i.id}`,'small','pencil')}${btn('Review',`review:${i.id}`,'small','flag')}</div></article>`}).join('')}</div><aside class="card evidence-panel"><h3>Evidence drawer</h3><div id="evidence-content">${evidenceHtml(state.evidence)}</div></aside></div></section>`}
function evidenceHtml(id){if(!id)return `<div class="evidence-empty">${icon('scan-search',24)}<br>Select an evidence chip to inspect the exact local source.</div>`;if(id.startsWith('paper:')){const p=D.papers.find(x=>x.id===id.split(':')[1]);return `<div class="evidence-record"><strong>${p?.title||id}</strong><span>${p?.authors.join(', ')} · ${p?.year}</span><p>${p?.abstract}</p>${badge('Local paper record','info')}</div>`}if(id.startsWith('cluster:')){const c=D.clusters.find(x=>x.id===id.split(':')[1]);return `<div class="evidence-record"><strong>${c?.name||id}</strong><span>${c?.count||'—'} papers · ${c?.share||'—'}% · mean year ${c?.year||'—'}</span><p>Top terms: ${c?.terms.join(', ')||'Static cluster evidence'}</p>${badge('Precomputed cluster','ai')}</div>`}if(id.startsWith('trend:')){const t=D.trend.find(x=>String(x.year)===id.split(':')[1]);return `<div class="evidence-record"><strong>Annual publication count</strong><span>${t?.year}: ${t?.count} papers${t?.partial?' · partial year':''}</span><p>Grouped from the local demo corpus metadata.</p>${badge('Descriptive statistic','info')}</div>`}if(id.startsWith('author:')){const a=D.authors.find(x=>x.name===id.split(':').slice(1).join(':'));return `<div class="evidence-record"><strong>${a?.name||id}</strong><span>${a?.papers||'—'} papers · ${a?.links||'—'} collaboration links</span><p>Exact-name normalization only; human disambiguation required.</p></div>`}return `<div class="evidence-record"><strong>${id}</strong><span>Validated local evidence identifier</span><p>This evidence belongs to the current frozen Demo Corpus.</p>${badge('Local evidence','success')}</div>`}
function render(){let content=state.page==='setup'?setupPage():state.page==='screening'?screeningPage():state.page==='explorer'?explorerPage():intelligencePage();$('#app').innerHTML=shell(content);applyProductCopy($('#app'));enhanceDataUI();lucide.createIcons({attrs:{'stroke-width':1.8}});bind();}
function bind(){
 $('#language-select')?.addEventListener('change',e=>set({lang:e.target.value}));
 $('#dataset-file')?.addEventListener('change',e=>{const file=e.target.files?.[0];if(file)importDataset(file)});
 const upload=$('.upload');if(upload){upload.ondragover=e=>{e.preventDefault();upload.classList.add('dragging')};upload.ondragleave=()=>upload.classList.remove('dragging');upload.ondrop=e=>{e.preventDefault();upload.classList.remove('dragging');const file=e.dataTransfer.files?.[0];if(file)importDataset(file)}}
 $$('[data-nav]').forEach(el=>el.onclick=()=>set({page:el.dataset.nav}));
 $$('[data-rule-tab]').forEach(el=>el.onclick=()=>set({ruleTab:el.dataset.ruleTab}));
 $$('[data-paper]').forEach(el=>el.onclick=()=>set({selectedPaper:el.dataset.paper}));
 $$('[data-decision]').forEach(el=>el.onclick=()=>decide(el.dataset.decision));
 $$('[data-explorer-tab]').forEach(el=>el.onclick=()=>set({explorerTab:el.dataset.explorerTab}));
 $$('[data-evidence]').forEach(el=>el.onclick=()=>{state.evidence=el.dataset.evidence;save();if(state.page==='intelligence'){$('#evidence-content').innerHTML=evidenceHtml(state.evidence);applyProductCopy($('#evidence-content'));lucide.createIcons()}else openEvidence(state.evidence)});
 $$('[data-keyword]').forEach(el=>el.onclick=()=>{const n=D.keywordNodes.find(x=>x.id===el.dataset.keyword);$$('.node').forEach(x=>x.classList.remove('selected'));el.classList.add('selected');$('#network-inspector').innerHTML=`<div class="evidence-record"><strong>${n.label}</strong><span>${n.value} papers · Cluster ${n.cluster}</span><p>Connected to ${D.keywordEdges.filter(e=>e.includes(n.id)).length} visible keywords.</p>${btn('Open evidence',`evidence:keyword:${n.label}`,'small','external-link')}</div>`;applyProductCopy($('#network-inspector'));lucide.createIcons();bindActions()});
 $$('[data-cluster]').forEach(el=>el.onclick=()=>openEvidence(`cluster:${el.dataset.cluster}`));
 $$('[data-tip]').forEach(el=>{el.onmouseenter=e=>showTip(e,el.dataset.tip);el.onmousemove=e=>moveTip(e);el.onmouseleave=hideTip});
 bindActions();
}
function bindActions(){$$('[data-action]').forEach(el=>el.onclick=()=>action(el.dataset.action))}
function decide(value){const old=state.decisions[state.selectedPaper];state.history.push({paper:state.selectedPaper,old,next:value});state.decisions[state.selectedPaper]=value;const reviewed=Object.keys(state.decisions).length;if(reviewed>=3&&state.contextVersion===1&&state.suggestion==='hidden')state.suggestion='available';const idx=D.papers.findIndex(x=>x.id===state.selectedPaper),next=D.papers[(idx+1)%D.papers.length];state.selectedPaper=next.id;save();render();notify(`${value[0].toUpperCase()+value.slice(1)} decision saved`)}
function action(a){
 if(a==='pick-file'){$('#dataset-file')?.click()}
 else if(a==='load-demo'){restoreSample();state={...state,loaded:true,realData:false,datasetName:'',datasetFormat:'',quality:null,parseStep:0,setup:false,corpus:false,decisions:{},history:[],contextVersion:0,suggestion:'hidden',selectedPaper:D.papers[0].id};save();render();let i=0;clearInterval(parseTimer);parseTimer=setInterval(()=>{i++;state.parseStep=i;save();render();if(i>=4){clearInterval(parseTimer);state.parseStep=4;save();notify(`Dataset ready · ${D.papers.length} records`)}} ,320)}
 else if(a==='confirm-setup'){if(!state.loaded){notify('Load the demo dataset first');return}set({setup:true,contextVersion:1,page:'screening'});notify('Research Context v1 confirmed')}
 else if(a==='go-screening')set({page:'screening'});
 else if(a==='undo'){const last=state.history.pop();if(!last){notify('No decision to undo');return}if(last.old)state.decisions[last.paper]=last.old;else delete state.decisions[last.paper];state.selectedPaper=last.paper;save();render();notify('Previous decision restored')}
 else if(a==='complete-demo'){D.papers.forEach(x=>{if(!state.decisions[x.id])state.decisions[x.id]=x.suggested});state.suggestion=state.contextVersion===1?'available':state.suggestion;save();render();notify('Remaining records completed with AI recommendations')}
 else if(a==='accept-context'||a==='edit-context'){if(a==='edit-context'){openDialog('Edit & accept context',`<div class="field"><label>New exclusion rule</label><textarea class="textarea" id="edited-rule">Exclude studies limited to architectural generation with no industrial or product design context.</textarea></div>`,`<button class="btn" data-action="close-dialog">Cancel</button><button class="btn primary" data-action="confirm-context-edit">Confirm Context v2</button>`);return}state.contextVersion=2;state.suggestion='accepted';save();render();notify('Context v2 active · 37 papers rescored')}
 else if(a==='reject-context'){state.suggestion='rejected';save();render();notify('Suggestion rejected · Context v1 unchanged')}
 else if(a==='finalize'){const c=counts(),remaining=datasetTotal()-c.reviewed;openDialog('Freeze Final Corpus',`<p>${remaining?`${remaining} records are not yet reviewed. Complete remaining screening before freezing the corpus.`:'The included records will be used for bibliometric computation and evidence-grounded insights.'}</p><div class="kpis" style="grid-template-columns:repeat(3,1fr)">${kpi(c.include,'Included','circle-check','success')}${kpi(c.boundary,'Boundary','triangle-alert','warning')}${kpi(c.exclude,'Excluded','circle-x')}</div><div class="limitation">${remaining?'Use AI recommendations to complete the remaining records, or continue manual review.':'Topic clustering and networks will be recalculated from the included corpus.'}</div>`,`<button class="btn" data-action="close-dialog">Cancel</button>${remaining?'':`<button class="btn primary" data-action="confirm-finalize">Freeze corpus</button>`}`)}
 else if(a==='confirm-finalize'){const included=D.papers.filter(p=>state.decisions[p.id]==='include');if(!included.length){notify('At least one included record is required');return}corpusPapers=included;const analysis=window.RESEARCH_ENGINE.analyze(included);D.trend=analysis.trend;D.keywordNodes=analysis.keywordNodes;D.keywordEdges=analysis.keywordEdges;D.authors=analysis.authors;D.clusters=analysis.clusters;D.insights=buildInsights(analysis,included);state.corpus=true;state.page='explorer';save();closeDialog();render();notify(`Final Corpus v1 frozen · ${included.length} papers`)}
 else if(a==='methodology')methodology();
 else if(a==='reset')openDialog('Reset interactive demo',`<p>Reset all screening decisions, Context changes, Corpus state and insight reviews?</p><div class="limitation">This only clears local browser state. Bundled fixture data remains unchanged.</div>`,`<button class="btn" data-action="close-dialog">Cancel</button><button class="btn danger" data-action="confirm-reset">Reset demo</button>`);
 else if(a==='confirm-reset'){localStorage.removeItem(KEY);restoreSample();state={...initial,decisions:{},history:[],reviews:{},editedInsights:{}};closeDialog();render();notify('Workspace restored to its initial state')}
 else if(a==='tour')openDialog('Guided demo path',`<ol style="line-height:2;color:var(--ca-ink-2)"><li>Load the bundled dataset in Research Setup.</li><li>Confirm Context v1 and review three papers.</li><li>Accept the Adaptive Context suggestion.</li><li>Complete demo decisions and freeze the corpus.</li><li>Explore four bibliometric views.</li><li>Open evidence and verify Research Insights.</li></ol>`,`<button class="btn primary" data-action="close-dialog">Got it</button>`);
 else if(a==='close-dialog')closeDialog();
 else if(a==='confirm-context-edit'){state.contextVersion=2;state.suggestion='accepted';save();closeDialog();render();notify('Edited rule saved in Context v2')}
 else if(a.startsWith('verify:')){state.reviews[a.split(':')[1]]='verified';save();render();notify('Insight marked as researcher verified')}
 else if(a.startsWith('review:')){state.reviews[a.split(':')[1]]='needs_review';save();render();notify('Insight marked for further review')}
 else if(a.startsWith('edit-insight:')){const id=a.split(':')[1],i=D.insights.find(x=>x.id===id);openDialog('Edit insight',`<div class="field"><label>Researcher-edited claim</label><textarea class="textarea" id="insight-edit">${state.editedInsights[id]||i.claim}</textarea></div><div class="limitation">The original simulated output remains in the fixture. This edit is stored locally.</div>`,`<button class="btn" data-action="close-dialog">Cancel</button><button class="btn primary" data-action="save-insight:${id}">Save edit</button>`)}
 else if(a.startsWith('save-insight:')){const id=a.split(':')[1];state.editedInsights[id]=$('#insight-edit').value;save();closeDialog();render();notify('Researcher edit saved locally')}
 else if(a.startsWith('evidence:'))openEvidence(a.split(':').slice(1).join(':'));
}
function methodology(){const q=state.quality||{},c=counts();openDialog('Methodology preview',`<div class="evidence-record"><strong>Dataset</strong><span>${state.datasetName||'Project dataset'} · ${state.datasetFormat||'Normalized records'} · ${datasetTotal()} accepted${q.duplicates!=null?` · ${q.duplicates} duplicates removed`:''}</span></div><div class="evidence-record"><strong>Adaptive Research Context</strong><span>Context v1 → v${state.contextVersion||1} · researcher-confirmed rules</span></div><div class="evidence-record"><strong>Screening</strong><span>Semantic and rule-assisted ranking · ${c.reviewed}/${datasetTotal()} decisions · researcher decisions take priority</span></div><div class="evidence-record"><strong>Final Corpus</strong><span>${state.corpus?`Frozen snapshot v1 · ${corpusTotal()} included`:'Not frozen'}</span></div><div class="evidence-record"><strong>Bibliometrics</strong><span>Annual grouping · keyword co-occurrence · exact-name author collaboration · TF-IDF + k-means topic clustering</span></div><div class="evidence-record"><strong>Evidence coverage</strong><span>${D.insights.length} of ${D.insights.length} AI insights reference corpus statistics, clusters, authors or papers</span></div><div class="limitation" style="margin-top:12px"><strong>Methodology note:</strong> Results describe the current imported and screened corpus. Topic labels, author identity and Potential Research Opportunities require researcher validation.</div>`,`<button class="btn primary" data-action="close-dialog">Close preview</button>`)}
function openEvidence(id){openDialog('Evidence inspector',evidenceHtml(id),`<button class="btn primary" data-action="close-dialog">Close</button>`)}
function openDialog(title,body,foot){$('#overlay-root').innerHTML=`<div class="overlay" role="presentation"><div class="dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><div class="dialog-head"><h2 id="dialog-title">${title}</h2><button class="icon-btn" data-action="close-dialog" aria-label="Close dialog">${icon('x')}</button></div><div class="dialog-body">${body}</div><div class="dialog-foot">${foot}</div></div></div>`;applyProductCopy($('#overlay-root'));lucide.createIcons({attrs:{'stroke-width':1.8}});bindActions();$('.dialog button')?.focus()}
function closeDialog(){$('#overlay-root').innerHTML=''}
function showTip(e,text){let t=$('.tooltip');if(!t){document.body.insertAdjacentHTML('beforeend','<div class="tooltip"></div>');t=$('.tooltip')}t.textContent=text;t.style.display='block';moveTip(e)}function moveTip(e){const t=$('.tooltip');if(t){t.style.left=`${Math.min(e.clientX+12,innerWidth-180)}px`;t.style.top=`${e.clientY-38}px`}}function hideTip(){const t=$('.tooltip');if(t)t.style.display='none'}
document.addEventListener('keydown',e=>{if($('.overlay')){if(e.key==='Escape')closeDialog();return}if(state.page==='screening'){if(e.key.toLowerCase()==='i')decide('include');if(e.key.toLowerCase()==='e')decide('exclude');if(e.key.toLowerCase()==='b')decide('boundary');if(e.key.toLowerCase()==='z')action('undo')}});
render();
})();
