window.DEMO_DATA = {
  papers: [
    {id:'P-001',title:'Co-creating Product Concepts with Generative AI: A Designer-in-the-Loop Study',authors:['Maya Chen','Oliver Hart'],year:2025,source:'Design Studies',doi:'10.1016/j.destud.2025.10421',keywords:['generative AI','co-creation','product design'],score:94,confidence:92,suggested:'include',rules:['IN-01','IN-03'],reason:'研究直接考察生成式 AI 在产品概念共创中的作用，并包含设计师反馈。',evidence:['“product concept generation”','“designer-in-the-loop”'],abstract:'This study investigates how industrial designers collaborate with generative AI during early-stage product concept development. A controlled workshop compares ideation breadth, iteration behavior, and designer agency across AI-assisted and conventional workflows.'},
    {id:'P-002',title:'Text-to-Image Models as Ideation Partners in Industrial Design Education',authors:['Sofia Martinez','Jin Park'],year:2024,source:'International Journal of Design',doi:'10.17028/ijd.2024.8831',keywords:['text-to-image','industrial design','education'],score:89,confidence:88,suggested:'include',rules:['IN-01','IN-02'],reason:'研究对象是工业设计教育，讨论生成模型辅助设计构思。',evidence:['“industrial design students”','“ideation partner”'],abstract:'The paper evaluates text-to-image systems as ideation partners for industrial design students, focusing on visual exploration, fixation, authorship, and critique practices.'},
    {id:'P-003',title:'Generative Algorithms for Lightweight Lattice Structures in Additive Manufacturing',authors:['Ethan Brooks','Lei Wu'],year:2023,source:'Additive Manufacturing',doi:'10.1016/j.addma.2023.103992',keywords:['generative design','lattice','manufacturing'],score:32,confidence:91,suggested:'exclude',rules:['EX-02'],reason:'研究聚焦制造结构优化，没有工业设计过程、用户或创意协作语境。',evidence:['“structural optimization”','“lattice structures”'],abstract:'A topology-driven generative algorithm optimizes lattice structures for additive manufacturing under mechanical load and material constraints.'},
    {id:'P-004',title:'Human–AI Collaboration in Creative Design: Roles, Agency and Evaluation',authors:['Amina Rahman','Tobias Klein'],year:2024,source:'AI & Society',doi:'10.1007/s00146-024-01988-2',keywords:['human-AI collaboration','creative design','agency'],score:76,confidence:64,suggested:'boundary',rules:['BD-01','IN-03'],reason:'与创意设计高度相关，但摘要未明确工业设计或产品设计场景。',evidence:['“creative design practice”','应用领域未明确'],abstract:'Through interviews and creative tasks, the study develops a role taxonomy for human–AI collaboration in design practice. The application domain spans multiple creative disciplines.'},
    {id:'P-005',title:'Diffusion Models for Automated Architectural Façade Generation',authors:['Noah Wilson','Eva Rossi'],year:2025,source:'Automation in Construction',doi:'10.1016/j.autcon.2025.105612',keywords:['diffusion model','architecture','façade'],score:28,confidence:95,suggested:'exclude',rules:['EX-01'],reason:'仅讨论建筑立面生成，不涉及工业或产品设计。',evidence:['“architectural façade”','“building envelope”'],abstract:'A conditional diffusion framework generates architectural façade alternatives from environmental and zoning constraints.'},
    {id:'P-006',title:'From Prompt to Prototype: Generative AI in Early-stage Product Development',authors:['Hannah Lee','Marco Silva'],year:2025,source:'Journal of Product Innovation Management',doi:'10.1111/jpim.12742',keywords:['prompting','prototype','product development'],score:96,confidence:95,suggested:'include',rules:['IN-01','IN-02'],reason:'明确覆盖从提示词到产品原型的早期工业设计流程。',evidence:['“early-stage product development”','“physical prototype”'],abstract:'We examine prompt-based image and 3D generation across the fuzzy front end of product development, tracing how design teams move from briefs to physical prototypes.'},
    {id:'P-007',title:'AI-assisted Molecule Design with Constraint-aware Language Models',authors:['Daniel Kim','Priya Shah'],year:2023,source:'Nature Machine Intelligence',doi:'10.1038/s42256-023-00721-4',keywords:['drug design','language model','molecule'],score:12,confidence:98,suggested:'exclude',rules:['EX-03'],reason:'“design”指药物分子设计，与产品/工业设计无关。',evidence:['“molecule design”','“drug candidates”'],abstract:'Constraint-aware language models generate molecular candidates with desired biochemical properties for drug discovery.'},
    {id:'P-008',title:'Designing with Machines: Changing Practices in Consumer Electronics Teams',authors:['Lina Andersson','Wei Zhao'],year:2022,source:'Design Issues',doi:'10.1162/desi_a_00691',keywords:['AI tools','design practice','consumer electronics'],score:85,confidence:82,suggested:'include',rules:['IN-03'],reason:'聚焦消费电子产品团队与 AI 工具的协作实践。',evidence:['“consumer electronics design teams”','“AI-assisted practice”'],abstract:'An ethnographic account of how consumer electronics teams integrate machine-learning tools into concept selection, styling, and cross-functional communication.'},
    {id:'P-009',title:'Generative Visual Systems and Creative Confidence among Novice Designers',authors:['Grace Liu','Sam Patel'],year:2024,source:'Creativity Research Journal',keywords:['creative confidence','novice designers','generative systems'],score:69,confidence:58,suggested:'boundary',rules:['BD-01'],reason:'讨论设计学习，但具体设计专业与产品语境不足。',evidence:['“novice designers”','discipline not reported'],abstract:'This experiment measures creative confidence and fixation among novice designers using generative visual systems. Participants came from several unspecified design programmes.'},
    {id:'P-010',title:'Responsible Generative AI for Sustainable Product Design Decisions',authors:['Klara Novak','Yuto Sato'],year:2025,source:'Sustainable Production and Consumption',doi:'10.1016/j.spc.2025.02.018',keywords:['responsible AI','sustainable design','decision support'],score:91,confidence:90,suggested:'include',rules:['IN-01','IN-04'],reason:'直接研究生成式 AI 支持可持续产品设计决策。',evidence:['“sustainable product design”','“decision support”'],abstract:'The study proposes and evaluates a responsible generative AI workflow for material choice, lifecycle scenarios, and trade-off communication in sustainable product design.'},
    {id:'P-011',title:'A Review of Artificial Intelligence in Design Research',authors:['Isabelle Moore','Kai Huang'],year:2021,source:'Design Science',doi:'10.1017/dsj.2021.28',keywords:['artificial intelligence','design research','review'],score:71,confidence:61,suggested:'boundary',rules:['BD-02'],reason:'覆盖广泛设计研究，可能包含相关材料，但摘要无法确定生成式 AI 与工业设计交集。',evidence:['“design research”','broad review scope'],abstract:'This review maps artificial intelligence methods across design research, including optimization, creativity support, engineering design, and interaction design.'},
    {id:'P-012',title:'Prompt Literacy for Professional Product Designers',authors:['Nora Ibrahim','Lucas Meyer'],year:2024,source:'The Design Journal',doi:'10.1080/14606925.2024.22911',keywords:['prompt literacy','product designer','workflow'],score:93,confidence:93,suggested:'include',rules:['IN-01','IN-03'],reason:'明确关注专业产品设计师使用生成式 AI 的提示能力与工作流。',evidence:['“professional product designers”','“generative AI workflows”'],abstract:'Based on field studies with professional product designers, this paper defines prompt literacy and examines its influence on iteration, control, and communication.'}
  ],
  trend:[{year:2017,count:8},{year:2018,count:11},{year:2019,count:17},{year:2020,count:24},{year:2021,count:39},{year:2022,count:63},{year:2023,count:108},{year:2024,count:151},{year:2025,count:187},{year:2026,count:46,partial:true}],
  keywordNodes:[
    {id:'k1',label:'Generative AI',value:126,x:48,y:44,cluster:1},{id:'k2',label:'Product design',value:94,x:29,y:57,cluster:1},{id:'k3',label:'Co-creation',value:71,x:63,y:62,cluster:2},{id:'k4',label:'Creativity',value:64,x:74,y:40,cluster:2},{id:'k5',label:'Human–AI',value:58,x:57,y:23,cluster:2},{id:'k6',label:'Prototyping',value:43,x:20,y:31,cluster:1},{id:'k7',label:'Sustainability',value:38,x:38,y:76,cluster:3},{id:'k8',label:'Design education',value:35,x:79,y:73,cluster:4},{id:'k9',label:'Prompting',value:49,x:42,y:18,cluster:4}
  ],
  keywordEdges:[['k1','k2',42],['k1','k3',38],['k1','k5',31],['k1','k9',29],['k2','k6',24],['k2','k7',18],['k3','k4',27],['k3','k5',22],['k4','k8',14],['k8','k9',16],['k2','k3',25]],
  authors:[
    {name:'Maya Chen',papers:12,links:8},{name:'Oliver Hart',papers:10,links:7},{name:'Jin Park',papers:9,links:6},{name:'Sofia Martinez',papers:8,links:5},{name:'Amina Rahman',papers:7,links:6},{name:'Tobias Klein',papers:6,links:4}
  ],
  clusters:[
    {id:'C1',name:'AI-assisted concept generation',count:76,share:35.5,year:2024.1,terms:['concept generation','product form','prototyping'],color:'#3E5ABD',paper:'P-006'},
    {id:'C2',name:'Human–AI co-creation',count:58,share:27.1,year:2024.4,terms:['co-creation','agency','designer-in-the-loop'],color:'#6857F5',paper:'P-001'},
    {id:'C3',name:'Responsible & sustainable design',count:43,share:20.1,year:2023.8,terms:['sustainability','responsible AI','materials'],color:'#0EA5C6',paper:'P-010'},
    {id:'C4',name:'Education & prompt literacy',count:37,share:17.3,year:2023.9,terms:['design education','prompting','creative confidence'],color:'#64748B',paper:'P-002'}
  ],
  insights:[
    {id:'I1',type:'Descriptive finding',title:'2023 年后相关研究快速增多',claim:'当前语料统计显示，2024 年收录 151 篇，较 2023 年的 108 篇增加 39.8%。',evidence:['trend:2023','trend:2024'],limit:'2026 年数据仅覆盖部分月份，不能与完整年度直接比较。'},
    {id:'I2',type:'Topic structure',title:'概念生成仍是最大的主题簇',claim:'AI-assisted concept generation 包含 76 篇，占 Final Corpus 的 35.5%，主要连接产品形态生成与快速原型。',evidence:['cluster:C1','paper:P-006'],limit:'主题标签来自分析引擎，需要结合代表文献进行人工验证。'},
    {id:'I3',type:'Interpretation',title:'人机共创研究正从工具采用转向能动性',claim:'Human–AI co-creation 簇的平均年份为 2024.4，代表文献集中讨论角色分配、控制与设计师能动性。',evidence:['cluster:C2','paper:P-001'],limit:'平均年份只能描述语料分布，不能证明研究范式已经转变。'},
    {id:'I4',type:'Collaboration pattern',title:'合作网络呈现若干小型核心团队',claim:'高产作者之间形成多个相对紧密的小型合作群，Maya Chen 在作者网络中拥有 8 个合作连接。',evidence:['author:Maya Chen','network:authors'],limit:'当前分析仅进行姓名完全匹配，未解决同名作者问题。'},
    {id:'I5',type:'Potential Research Opportunity',title:'设计评价与人机共创的连接值得进一步验证',claim:'共创主题与设计评价相关词的直接共现较少，可能形成 Underexplored Connection。',evidence:['cluster:C2','keyword:Co-creation'],limit:'共现较少不等于研究不存在；需要全文阅读和领域专家验证。',requiresValidation:true},
    {id:'I6',type:'Potential Research Opportunity',title:'可持续设计中的生成式 AI 决策透明度',claim:'可持续设计簇强调材料与生命周期，但与可解释决策相关的连接相对稀疏，值得进一步验证。',evidence:['cluster:C3','paper:P-010'],limit:'该判断仅基于当前语料与关键词网络，不能作为确定的研究空白。',requiresValidation:true}
  ]
};
