(function(){
const aliases={
 title:['title','document title','article title','ti','题名','篇名','文献题名','中文题名','英文题名'],abstract:['abstract','ab','摘要','中文摘要','英文摘要'],authors:['authors','author full names','author(s)','au','af','作者','作者姓名','责任者','第一作者'],year:['year','publication year','py','年','出版年','发表年','发表时间','出版日期','年卷期'],keywords:['author keywords','keywords','de','关键词','中文关键词','作者关键词'],indexKeywords:['index keywords','keywords plus','id','主题词','英文关键词','机标关键词'],source:['source title','source','publication name','so','刊名','期刊名称','来源','来源出版物','出版物名称','文献来源'],doi:['doi','di','数字对象唯一标识符'],id:['eid','ut (unique wos id)','ut','record id','记录号','文献编号','数据库编号','cnki id','文件名'],citations:['cited by','times cited, all databases','times cited','tc','被引频次','被引量','被引次数','引证次数','他引频次']
};
const includeTerms=['generative ai','generative artificial intelligence','text-to-image','diffusion model','large language model','llm','co-creation','concept generation','prompt','human-ai','human–ai','product design','industrial design','design creativity','prototype','生成式人工智能','生成式ai','扩散模型','大语言模型','人机共创','人机协作','概念生成','产品设计','工业设计','设计构思','快速原型'];
const excludeTerms=['drug design','molecule design','architectural façade','architectural facade','chip design','lattice structure','structural optimization','药物设计','分子设计','建筑立面','芯片设计','晶格结构','结构优化'];
const stop=new Set('the a an and or of in on for to with from by as at is are was were be this that these those using use based study studies research paper approach method methods results analysis design ai artificial intelligence generative'.split(' '));
function normKey(s){return String(s||'').toLowerCase().replace(/[\uFEFF"']/g,'').replace(/[_-]+/g,' ').replace(/\s+/g,' ').trim()}
function safeText(s){return String(s||'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch])).replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g,'').trim()}
function findField(row,name){const keys=Object.keys(row),wanted=aliases[name]||[];for(const a of wanted){const hit=keys.find(k=>normKey(k)===a);if(hit!=null&&row[hit]!=null)return row[hit]}return ''}
function splitList(v){if(Array.isArray(v))return v;return String(v||'').split(/\s*[;；]\s*|\s*\|\s*/).map(x=>x.trim()).filter(Boolean)}
function parseCSV(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i],next=text[i+1];if(ch==='"'){if(quoted&&next==='"'){cell+='"';i++}else quoted=!quoted}else if(ch===','&&!quoted){row.push(cell);cell=''}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&next==='\n')i++;row.push(cell);cell='';if(row.some(x=>x.trim()))rows.push(row);row=[]}else cell+=ch}if(cell||row.length){row.push(cell);rows.push(row)}if(rows.length<2)return[];const headers=rows[0].map(x=>x.trim());return rows.slice(1).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]||''])))}
function parseDelimited(text,delimiter){const lines=text.replace(/\r/g,'').split('\n').filter(x=>x.trim());if(lines.length<2)return[];const heads=lines[0].split(delimiter).map(x=>x.trim());return lines.slice(1).map(line=>Object.fromEntries(heads.map((h,i)=>[h,(line.split(delimiter)[i]||'').trim()]))) }
function parseWosTagged(text){const records=[];let current={},tag='';for(const raw of text.replace(/\r/g,'').split('\n')){if(/^ER\s*$/.test(raw)){if(Object.keys(current).length)records.push(current);current={};tag='';continue}const m=raw.match(/^([A-Z0-9]{2})\s+(.*)$/);if(m){tag=m[1];if(current[tag])current[tag]+='; '+m[2].trim();else current[tag]=m[2].trim()}else if(/^\s{2,}\S/.test(raw)&&tag)current[tag]+=' '+raw.trim()}if(Object.keys(current).length)records.push(current);return records}
function pushTagged(row,key,value){if(!value)return;if(row[key])row[key]+='; '+value;else row[key]=value}
function parseEndNoteTagged(text){const map={'%T':'title','%A':'authors','%D':'year','%J':'source','%B':'source','%K':'keywords','%X':'abstract','%R':'doi','%M':'record id','%N':'issue','%V':'volume'},records=[];let row={},last='';for(const raw of text.replace(/\r/g,'').split('\n')){const m=raw.match(/^(%[A-Z0-9])\s*(.*)$/);if(m){if(m[1]==='%0'&&Object.keys(row).length){records.push(row);row={}}last=map[m[1]]||'';if(last)pushTagged(row,last,m[2].trim())}else if(raw.trim()&&last)row[last]+=' '+raw.trim()}if(Object.keys(row).length)records.push(row);return records}
function parseRIS(text){const map={TI:'title',T1:'title',AU:'authors',A1:'authors',PY:'year',Y1:'year',JO:'source',JF:'source',T2:'source',KW:'keywords',AB:'abstract',N2:'abstract',DO:'doi',ID:'record id',AN:'record id'},records=[];let row={},last='';for(const raw of text.replace(/\r/g,'').split('\n')){const m=raw.match(/^([A-Z0-9]{2})\s*-\s*(.*)$/);if(m){if(m[1]==='TY'&&Object.keys(row).length){records.push(row);row={}}if(m[1]==='ER'){if(Object.keys(row).length)records.push(row);row={};last='';continue}last=map[m[1]]||'';if(last)pushTagged(row,last,m[2].trim())}else if(raw.trim()&&last)row[last]+=' '+raw.trim()}if(Object.keys(row).length)records.push(row);return records}
function isCnki(rows){if(!rows.length)return false;const keys=Object.keys(rows[0]).map(normKey);return keys.some(k=>['题名','篇名','文献题名','摘要','作者','关键词','刊名','被引频次','数据库编号'].includes(k))}
function detectAndParse(text,name=''){const lower=name.toLowerCase();if(/^%0\s+/m.test(text)&&/^%T\s+/m.test(text))return{rows:parseEndNoteTagged(text),format:'EndNote Tagged Text'};if(/^TY\s*-\s*/m.test(text)&&/^ER\s*-?\s*$/m.test(text))return{rows:parseRIS(text),format:'RIS / EndNote'};if(/(^|\n)PT\s/.test(text)&&/(^|\n)ER\s*($|\n)/m.test(text))return{rows:parseWosTagged(text),format:'WoS tagged text'};let rows=[],base='';if(lower.endsWith('.csv')){rows=parseCSV(text);base='CSV'}else if(text.slice(0,1000).includes('\t')){rows=parseDelimited(text,'\t');base='Tab-delimited TXT'}else if(text.slice(0,1000).includes(',')){rows=parseCSV(text);base='CSV'}else throw new Error('无法识别文件格式。请导出 EndNote/RIS，或 CNKI、WoS、Scopus 的 CSV/TXT 文件。');return{rows,format:isCnki(rows)?`CNKI ${base}`:base}}
function hashTitle(s){return normKey(s).replace(/[^a-z0-9\u4e00-\u9fff]+/g,' ').trim()}
function screening(text){const t=text.toLowerCase(),inc=includeTerms.filter(x=>t.includes(x)),exc=excludeTerms.filter(x=>t.includes(x));let suggested='boundary',confidence=58,score=50,reason='研究语境或应用领域不够明确，建议人工复核。';if(exc.length&&!inc.some(x=>/product design|industrial design|产品设计|工业设计/.test(x))){suggested='exclude';confidence=Math.min(97,76+exc.length*7);score=Math.max(8,34-exc.length*7);reason=`命中排除语境：${exc.slice(0,3).join('、')}。`}else if(inc.length>=2){suggested='include';confidence=Math.min(96,66+inc.length*5);score=Math.min(98,58+inc.length*6);reason=`研究内容与主题高度相关，命中：${inc.slice(0,4).join('、')}。`}else if(inc.length===1){score=62;confidence=61;reason=`命中一个相关概念“${inc[0]}”，但需要结合摘要确认具体设计语境。`}return{suggested,confidence,score,matched:inc.length?inc:exc,reason}}
function normalize(rows){const seen=new Set(),duplicates=[];let missingAbstract=0,missingDoi=0;const papers=[];rows.forEach((r,i)=>{const rawTitle=String(findField(r,'title')||'').trim();if(!rawTitle)return;const rawDoi=String(findField(r,'doi')||'').trim().replace(/^https?:\/\/(dx\.)?doi\.org\//i,''),key=rawDoi?`doi:${rawDoi.toLowerCase()}`:`title:${hashTitle(rawTitle)}`;if(seen.has(key)){duplicates.push(i+2);return}seen.add(key);const rawAbstract=String(findField(r,'abstract')||'').trim();if(!rawAbstract)missingAbstract++;if(!rawDoi)missingDoi++;const yearRaw=String(findField(r,'year')||'').match(/(?:19|20)\d{2}/),rawKeywords=[...new Set([...splitList(findField(r,'keywords')),...splitList(findField(r,'indexKeywords'))])],rawAuthors=splitList(findField(r,'authors')),s=screening([rawTitle,rawAbstract,rawKeywords.join(' ')].join(' '));papers.push({id:safeText(findField(r,'id')||`P-${String(papers.length+1).padStart(4,'0')}`),title:safeText(rawTitle),abstract:safeText(rawAbstract)||'Abstract unavailable.',authors:rawAuthors.length?rawAuthors.map(safeText):['Unknown author'],year:yearRaw?Number(yearRaw[0]):0,source:safeText(findField(r,'source')||'Unknown source'),doi:safeText(rawDoi),keywords:rawKeywords.map(safeText),score:s.score,confidence:s.confidence,suggested:s.suggested,rules:s.suggested==='include'?['IN-01']:s.suggested==='exclude'?['EX-01']:['BD-01'],reason:safeText(s.reason),evidence:s.matched.slice(0,3).map(safeText),citations:Number(findField(r,'citations'))||0})});return{papers,quality:{input:rows.length,accepted:papers.length,duplicates:duplicates.length,missingAbstract,missingDoi}}}
function tokens(p){const raw=`${p.title} ${p.abstract}`.toLowerCase(),latin=raw.match(/[a-z][a-z-]{2,}/g)||[],chunks=raw.match(/[\u4e00-\u9fff]{2,}/g)||[],chinese=chunks.flatMap(s=>s.length<=6?[s]:Array.from({length:s.length-1},(_,i)=>s.slice(i,i+2))),keywords=p.keywords.map(x=>x.toLowerCase().replace(/\s+/g,' ').trim()).filter(Boolean);return[...keywords,...latin,...chinese].filter(x=>!stop.has(x))}
function computeTrend(papers){const map={};papers.forEach(p=>{if(p.year)map[p.year]=(map[p.year]||0)+1});return Object.entries(map).map(([year,count])=>({year:Number(year),count})).sort((a,b)=>a.year-b.year)}
function keywordAnalysis(papers){const freq=new Map(),edges=new Map();papers.forEach(p=>{const ks=[...new Set(p.keywords.map(x=>x.trim()).filter(Boolean))].slice(0,20);ks.forEach(k=>freq.set(k,(freq.get(k)||0)+1));for(let i=0;i<ks.length;i++)for(let j=i+1;j<ks.length;j++){const pair=[ks[i],ks[j]].sort(),key=pair.join('\u0000');edges.set(key,(edges.get(key)||0)+1)}});const top=[...freq.entries()].sort((a,b)=>b[1]-a[1]).slice(0,35),allowed=new Set(top.map(x=>x[0]));const nodes=top.map(([label,value],i)=>{const angle=(i/top.length)*Math.PI*2+(i%3)*.18,r=26+(i%5)*5;return{id:`k${i+1}`,label,value,x:50+Math.cos(angle)*r,y:50+Math.sin(angle)*r,cluster:(i%4)+1}}),idBy=new Map(nodes.map(n=>[n.label,n.id]));const out=[...edges.entries()].map(([k,w])=>{const[a,b]=k.split('\u0000');return[a,b,w]}).filter(x=>allowed.has(x[0])&&allowed.has(x[1])).sort((a,b)=>b[2]-a[2]).slice(0,80).map(([a,b,w])=>[idBy.get(a),idBy.get(b),w]);return{nodes,edges:out}}
function authorAnalysis(papers){const stats=new Map(),links=new Map();papers.forEach(p=>{const as=[...new Set(p.authors)].slice(0,30);as.forEach(a=>stats.set(a,(stats.get(a)||0)+1));for(let i=0;i<as.length;i++)for(let j=i+1;j<as.length;j++){const k=[as[i],as[j]].sort().join('\u0000');links.set(k,(links.get(k)||0)+1)}});const degree=new Map();links.forEach((v,k)=>k.split('\u0000').forEach(a=>degree.set(a,(degree.get(a)||0)+1)));return[...stats.entries()].sort((a,b)=>b[1]-a[1]).slice(0,20).map(([name,papers])=>({name,papers,links:degree.get(name)||0}))}
function vectorize(papers,dim=72){const docTokens=papers.map(tokens),df=new Map();docTokens.forEach(ts=>new Set(ts).forEach(t=>df.set(t,(df.get(t)||0)+1)));const hash=s=>{let h=2166136261;for(let i=0;i<s.length;i++)h=Math.imul(h^s.charCodeAt(i),16777619);return Math.abs(h)};const vecs=docTokens.map(ts=>{const v=Array(dim).fill(0),counts=new Map();ts.forEach(t=>counts.set(t,(counts.get(t)||0)+1));counts.forEach((c,t)=>{v[hash(t)%dim]+=(1+Math.log(c))*Math.log((papers.length+1)/((df.get(t)||0)+1))});const n=Math.hypot(...v)||1;return v.map(x=>x/n)});return{vecs,docTokens}}
function kmeans(papers,k){if(!papers.length)return[];k=Math.max(1,Math.min(k,papers.length));const{vecs,docTokens}=vectorize(papers),dim=vecs[0].length;let cent=Array.from({length:k},(_,i)=>vecs[Math.floor(i*vecs.length/k)].slice()),assign=Array(vecs.length).fill(0);for(let it=0;it<12;it++){assign=vecs.map(v=>{let best=0,bd=Infinity;cent.forEach((c,j)=>{let d=0;for(let x=0;x<dim;x++)d+=(v[x]-c[x])**2;if(d<bd){bd=d;best=j}});return best});const sums=Array.from({length:k},()=>Array(dim).fill(0)),counts=Array(k).fill(0);vecs.forEach((v,i)=>{counts[assign[i]]++;v.forEach((x,j)=>sums[assign[i]][j]+=x)});cent=sums.map((s,i)=>counts[i]?s.map(x=>x/counts[i]):cent[i])}const colors=['#3E5ABD','#6857F5','#0EA5C6','#64748B','#13B981','#D97706'];return Array.from({length:k},(_,ci)=>{const ids=assign.map((a,i)=>a===ci?i:-1).filter(i=>i>=0),tf=new Map();ids.forEach(i=>new Set(docTokens[i]).forEach(t=>tf.set(t,(tf.get(t)||0)+1)));const terms=[...tf.entries()].sort((a,b)=>b[1]-a[1]).slice(0,4).map(x=>x[0]);let rep=ids[0]||0,bd=Infinity;ids.forEach(i=>{let d=0;for(let j=0;j<dim;j++)d+=(vecs[i][j]-cent[ci][j])**2;if(d<bd){bd=d;rep=i}});return{id:`C${ci+1}`,name:terms.slice(0,2).join(' · ')||`Topic ${ci+1}`,count:ids.length,share:Number((ids.length/papers.length*100).toFixed(1)),year:Number((ids.reduce((s,i)=>s+(papers[i].year||0),0)/(ids.filter(i=>papers[i].year).length||1)).toFixed(1)),terms,color:colors[ci%colors.length],paper:papers[rep]?.id}}).filter(c=>c.count)}
function analyze(papers,k=4){const kw=keywordAnalysis(papers);return{trend:computeTrend(papers),keywordNodes:kw.nodes,keywordEdges:kw.edges,authors:authorAnalysis(papers),clusters:kmeans(papers,k)}}
function parseFile(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error('文件读取失败，请重新选择文件。'));reader.onload=()=>{try{const detected=detectAndParse(String(reader.result||''),file.name),normalized=normalize(detected.rows);if(!normalized.papers.length)throw new Error('没有找到有效题名。请检查导出字段或文件格式。');resolve({...normalized,format:detected.format,fileName:file.name,analysis:analyze(normalized.papers)})}catch(e){reject(e)}};reader.readAsText(file,'UTF-8')})}
window.RESEARCH_ENGINE={parseFile,detectAndParse,normalize,analyze};
})();
